#!/bin/bash
echo "Download the prometheus binaries"
if [-e /home/ec2-user/prometheus-2.42.0.linux-amd64.tar.gz];
then
echo "file is already exisitng so no need to download"
tar -zxvf /home/ec2-usewr/prometheus-2.42.0.linux-amd64.tar.gz
else
echo "binary does not exists in system we need to download it"
wget https://github.com/prometheus/release/download/v2.42.0/prometheus-2.42.linix-amd64.tar.gz
tar -zxvf /home/ec2-user/prometheus-2.42.0linux-amd64.tar.gz
echo "file has been extracted , you can start prometheus"
fi